// Package semantic defines a bounded, offline semantic artifact. It is separate
// from legacy content-position graph IDs and is not a corpus-scale serving index.
// Publication belongs to internal/snapshot; this package only writes staged files.
package semantic

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
)

const FormatVersion = 1
const Format = "moedex.semantic"

type Artifact struct {
	Version     int              `json:"version"`
	Snapshots   []SourceSnapshot `json:"snapshots"`
	Contexts    []BuildContext   `json:"contexts"`
	Sources     []Source         `json:"sources"`
	Symbols     []Symbol         `json:"symbols"`
	Occurrences []Occurrence     `json:"occurrences"`
	Bindings    []Binding        `json:"bindings"`
	Diagnostics []Diagnostic     `json:"diagnostics,omitempty"`
}

type SourceSnapshot struct {
	ID        string `json:"id"`
	Repo      string `json:"repo"`
	ProjectID string `json:"project_id,omitempty"`
	Commit    string `json:"commit,omitempty"`
	// Origin is captured Git remote audit evidence, not proof of remote ownership.
	// Compact lookup indexes omit this field; the hashed audit artifact retains it.
	Origin           string `json:"origin,omitempty"`
	InputFingerprint string `json:"input_fingerprint"`
}

type BuildContext struct {
	ID                   string   `json:"id"`
	SnapshotID           string   `json:"snapshot_id"`
	Project              string   `json:"project"`
	InputFingerprint     string   `json:"input_fingerprint"`
	Extractor            string   `json:"extractor"`
	ExtractorVersion     string   `json:"extractor_version"`
	Status               string   `json:"status"`
	Issues               []string `json:"issues,omitempty"`
	SourceIDs            []string `json:"source_ids"`
	DependencyContextIDs []string `json:"dependency_context_ids,omitempty"`
	Capture              string   `json:"capture"`
	// DependencyBundleSHA256 identifies the exact offline manifest verified by
	// capture. Compact results omit this audit field but retain the context ID.
	DependencyBundleSHA256 string `json:"dependency_bundle_sha256,omitempty"`
}

// RawSHA256 and spans identify original source bytes, including any BOM. They
// must not be populated from the normalized content-store hash.
type Source struct {
	ID         string `json:"id"`
	SnapshotID string `json:"snapshot_id"`
	Path       string `json:"path"`
	RawSHA256  string `json:"raw_sha256"`
	ByteSize   uint64 `json:"byte_size"`
	Generated  bool   `json:"generated"`
	// Content retains ephemeral generated bytes, not ordinary repository blobs.
	Content []byte `json:"content,omitempty"`
}

// Namespace is an explicit qualified project, assembly, or package namespace.
// Package/assembly versions belong in that namespace. Descriptor must retain
// compiler signature and generic arity; source positions are not descriptors.
type SymbolKey struct {
	Language       string `json:"language"`
	NamespaceKind  string `json:"namespace_kind"`
	Namespace      string `json:"namespace"`
	Descriptor     string `json:"descriptor"`
	DescriptorKind string `json:"descriptor_kind"`
}
type Symbol struct {
	ID  string    `json:"id"`
	Key SymbolKey `json:"key"`
}

type Occurrence struct {
	ID        string `json:"id"`
	SourceID  string `json:"source_id"`
	ContextID string `json:"context_id"`
	Role      string `json:"role"`
	Kind      string `json:"kind"`
	Offset    uint64 `json:"offset"`
	Length    uint64 `json:"length"`
}

// Binding is the observed semantic fact. Resolved denotes compiler binding,
// never a guarantee about runtime dispatch. Diagnostic alternatives remain
// distinct from the resolved symbol.
type Binding struct {
	ID           string `json:"id"`
	OccurrenceID string `json:"occurrence_id"`
	Status       string `json:"status"`
	SymbolID     string `json:"symbol_id,omitempty"`
	// EnclosingSymbolID preserves compiler caller/owner evidence without
	// interpreting the reference as a runtime CALLS relationship.
	EnclosingSymbolID   string               `json:"enclosing_symbol_id,omitempty"`
	CandidateSymbolIDs  []string             `json:"candidate_symbol_ids,omitempty"`
	Method              string               `json:"method"`
	Extractor           string               `json:"extractor"`
	ExtractorVersion    string               `json:"extractor_version"`
	DomainFacts         []DomainFact         `json:"domain_facts,omitempty"`
	ImplementationFacts []ImplementationFact `json:"implementation_facts,omitempty"`
}

// Diagnostic retains compiler failure evidence, including locationless project
// errors. Source spans address raw bytes; zero-length insertion points are valid.
type Diagnostic struct {
	ID        string `json:"id"`
	ContextID string `json:"context_id"`
	Code      string `json:"code"`
	Severity  string `json:"severity"`
	Message   string `json:"message"`
	SourceID  string `json:"source_id,omitempty"`
	Offset    uint64 `json:"offset,omitempty"`
	Length    uint64 `json:"length,omitempty"`
}

func identity(kind string, value any) string {
	b, _ := json.Marshal(value) // these fixed record types cannot fail JSON encoding
	h := sha256.New()
	h.Write([]byte(Format + ".v1/" + kind + "\x00"))
	h.Write(b)
	return kind + ":" + hex.EncodeToString(h.Sum(nil))
}
func (s SourceSnapshot) ComputeID() string { s.ID = ""; return identity("snapshot", s) }
func (c BuildContext) ComputeID() string   { c.ID = ""; c.Capture = ""; return identity("context", c) }
func (s Source) ComputeID() string         { s.ID = ""; s.Content = nil; return identity("source", s) }
func (s Symbol) ComputeID() string         { return identity("symbol", s.Key) }
func (o Occurrence) ComputeID() string     { o.ID = ""; return identity("occurrence", o) }
func (b Binding) ComputeID() string        { b.ID = ""; return identity("binding", b) }
func (d Diagnostic) ComputeID() string     { d.ID = ""; return identity("diagnostic", d) }

// Complete is a publication eligibility check, not a substitute for Validate.
func (a *Artifact) Complete() bool {
	if a == nil || len(a.Contexts) == 0 {
		return false
	}
	for _, c := range a.Contexts {
		if c.Status != "complete" {
			return false
		}
	}
	return true
}
