//go:build lsp

package navigate

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"
)

func TestPoolManagedWorkspaceKeepsFakeLSPWritesOutOfCanonicalCorpus(t *testing.T) {
	_, repo, _ := newManagedWorkspaceFixture(t)
	cache := filepath.Join(t.TempDir(), "cache")
	canonicalFile := filepath.Join(repo, "src", "main.go")

	pool := NewPool(Config{
		Server:            os.Args[0],
		Args:              []string{"-test.run=^TestWorkspaceIsolationFakeLSPHelper$"},
		Env:               []string{"MOEDEX_FAKE_LSP_HELPER=1"},
		WorkspaceCacheDir: cache,
		RequestTimeout:    5 * time.Second,
	})
	t.Cleanup(func() { _ = pool.Close() })

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	locations, err := pool.Definition(ctx, Pos{File: canonicalFile, Line: 1, Col: 1})
	if err != nil {
		t.Fatalf("definition through isolated fake LSP: %v", err)
	}
	if len(locations) != 1 || locations[0].File != canonicalFile || locations[0].Start.File != canonicalFile {
		t.Fatalf("scratch result paths were not restored to canonical paths: %+v", locations)
	}

	canonicalGenerated := filepath.Join(repo, "src", "obj", "fake-lsp-generated.txt")
	if _, err := os.Stat(canonicalGenerated); !os.IsNotExist(err) {
		t.Fatalf("fake LSP mutated canonical corpus: %v", err)
	}
	matches, err := filepath.Glob(filepath.Join(cache, "v1", "corpus-*", "project-101", "*", workspaceTreeDir, "src", "obj", "fake-lsp-generated.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) != 1 {
		t.Fatalf("fake LSP output not found in isolated workspace: %v", matches)
	}
	if _, err := os.Stat(filepath.Join(repo, "src", "fake-lsp-cwd.txt")); !os.IsNotExist(err) {
		t.Fatalf("fake LSP relative write reached canonical corpus: %v", err)
	}
	cwdMatches, err := filepath.Glob(filepath.Join(cache, "v1", "corpus-*", "project-101", "*", workspaceTreeDir, "src", "fake-lsp-cwd.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if len(cwdMatches) != 1 {
		t.Fatalf("fake LSP relative output not found in isolated workspace CWD: %v", cwdMatches)
	}
}

// TestWorkspaceIsolationFakeLSPHelper becomes a minimal subprocess LSP when
// selected explicitly by TestPoolManagedWorkspaceKeepsFakeLSPWritesOutOfCanonicalCorpus.
// Its initialize handler deliberately writes beneath rootUri, proving the
// external process sees only the disposable projection.
func TestWorkspaceIsolationFakeLSPHelper(t *testing.T) {
	if os.Getenv("MOEDEX_FAKE_LSP_HELPER") != "1" {
		return
	}
	reader := bufio.NewReader(os.Stdin)
	for {
		body, err := readFrame(reader)
		if err != nil {
			os.Exit(0)
		}
		var request struct {
			ID     json.RawMessage        `json:"id"`
			Method string                 `json:"method"`
			Params map[string]interface{} `json:"params"`
		}
		if err := json.Unmarshal(body, &request); err != nil {
			continue
		}
		switch request.Method {
		case "initialize":
			rootURI, _ := request.Params["rootUri"].(string)
			root := uriToPath(rootURI)
			generated := filepath.Join(root, "obj", "fake-lsp-generated.txt")
			if err := os.MkdirAll(filepath.Dir(generated), 0o755); err != nil {
				os.Exit(2)
			}
			if err := os.WriteFile(generated, []byte("generated by fake LSP"), 0o644); err != nil {
				os.Exit(2)
			}
			if err := os.WriteFile("fake-lsp-cwd.txt", []byte("relative output"), 0o644); err != nil {
				os.Exit(2)
			}
			writeFakeLSPResponse(request.ID, map[string]interface{}{
				"capabilities": map[string]interface{}{
					"textDocumentSync": 1,
					"positionEncoding": "utf-8",
				},
			})
		case "textDocument/definition":
			doc, _ := request.Params["textDocument"].(map[string]interface{})
			uri, _ := doc["uri"].(string)
			writeFakeLSPResponse(request.ID, []map[string]interface{}{{
				"uri": uri,
				"range": map[string]interface{}{
					"start": map[string]int{"line": 0, "character": 0},
					"end":   map[string]int{"line": 0, "character": 1},
				},
			}})
		case "shutdown":
			writeFakeLSPResponse(request.ID, nil)
		case "exit":
			os.Exit(0)
		}
	}
}

func writeFakeLSPResponse(id json.RawMessage, result interface{}) {
	response, _ := json.Marshal(map[string]interface{}{
		"jsonrpc": "2.0",
		"id":      id,
		"result":  result,
	})
	_, _ = fmt.Fprintf(os.Stdout, "Content-Length: %d\r\n\r\n", len(response))
	_, _ = os.Stdout.Write(response)
}
