package candidates

import (
	"fmt"
	"math/rand"
	"reflect"
	"strings"
	"testing"

	"moedex/internal/index"
	"moedex/internal/trigram"
)

type occurrenceProvider struct {
	postings map[trigram.Trigram][]index.Posting
	selected map[trigram.Trigram]bool
	decoded  []trigram.Trigram
	counted  []trigram.Trigram
}

func (p *occurrenceProvider) Postings(g trigram.Trigram) []index.Posting {
	p.decoded = append(p.decoded, g)
	return p.postings[g]
}
func (p *occurrenceProvider) PostingCount(g trigram.Trigram) int {
	p.counted = append(p.counted, g)
	return len(p.postings[g])
}
func (p *occurrenceProvider) Trigrams() []trigram.Trigram {
	var out []trigram.Trigram
	for g := range p.postings {
		out = append(out, g)
	}
	return out
}
func (p *occurrenceProvider) IndexedGram(g trigram.Trigram) bool {
	return p.selected == nil || p.selected[g]
}
func lazyOccurrences(ix *index.Index, selected map[trigram.Trigram]bool) (*index.Index, *occurrenceProvider) {
	p := &occurrenceProvider{postings: map[trigram.Trigram][]index.Posting{}, selected: selected}
	for _, g := range ix.Trigrams() {
		if selected == nil || selected[g] {
			p.postings[g] = ix.Postings(g)
		}
	}
	return index.RestoreLazy(ix.Snapshot(), p), p
}
func occurrencePositions(ix *index.Index, needle []byte, positional bool) [][2]int {
	var out [][2]int
	add := func(blob uint64, _ []byte, off int) { out = append(out, [2]int{int(blob), off}) }
	if !positional || !positionalOccurrences(ix, needle, add) {
		scanOccurrences(ix, needle, add)
	}
	return out
}

// Generated byte strings cover overlaps, shared prefix/suffix false positives,
// multiple blobs, and matches whose interior gram also occurs near a boundary.
func TestPositionalOccurrencesScanParity(t *testing.T) {
	rng := rand.New(rand.NewSource(128))
	ix := index.New()
	for i := 0; i < 12; i++ {
		content := make([]byte, 600)
		for j := range content {
			content[j] = "abc_ "[rng.Intn(5)]
		}
		ix.AddFile("r", fmt.Sprint(i), "", fmt.Sprint(i), content)
	}
	lazy, _ := lazyOccurrences(ix, nil)
	selective, _ := lazyOccurrences(ix, map[trigram.Trigram]bool{{'a', 'b', 'c'}: true, {'a', 'a', 'a'}: true, {'b', 'b', 'b'}: true})
	for i := 0; i < 300; i++ {
		length := 3 + rng.Intn(15)
		blob := ix.Blob(uint64(rng.Intn(ix.NumBlobs())))
		offset := rng.Intn(len(blob.Content) - length)
		needle := blob.Content[offset : offset+length]
		want := occurrencePositions(ix, needle, false)
		for _, candidate := range []*index.Index{ix, lazy, selective} {
			if got := occurrencePositions(candidate, needle, true); !reflect.DeepEqual(got, want) {
				t.Fatalf("needle %q: got %v, want %v", needle, got, want)
			}
		}
	}
}

func TestPositionalOccurrencesDecodesSparseInteriorOnly(t *testing.T) {
	ix := index.New()
	ix.AddFile("r", "f", "", "sha", []byte(strings.Repeat("Pre Suf ", 1000)+"PreXYZSuf"))
	lazy, p := lazyOccurrences(ix, nil)
	want := occurrencePositions(ix, []byte("PreXYZSuf"), false)
	if got := occurrencePositions(lazy, []byte("PreXYZSuf"), true); !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	if len(p.decoded) != 1 || p.decoded[0] != (trigram.Trigram{'X', 'Y', 'Z'}) {
		t.Fatalf("decoded %v; expected sparse interior only", p.decoded)
	}
	if len(p.counted) != 1 {
		t.Fatalf("counted %v; sparse first probe should suffice", p.counted)
	}
}

func TestPositionalOccurrencesSelectedInteriorAndUnknownFallback(t *testing.T) {
	ix := index.New()
	ix.AddFile("r", "f", "", "sha", []byte("XYZ PreXYZSuf PreXXXSuf PreXYZSufXYZ"))
	needle := []byte("PreXYZSuf")
	for _, selected := range []map[trigram.Trigram]bool{
		{{'X', 'Y', 'Z'}: true}, {}, {{'n', 'o', 't'}: true},
	} {
		lazy, p := lazyOccurrences(ix, selected)
		want := occurrencePositions(ix, needle, false)
		if got := occurrencePositions(lazy, needle, true); !reflect.DeepEqual(got, want) {
			t.Fatalf("selected %v: got %v, want %v", selected, got, want)
		}
		for _, g := range p.counted {
			if !selected[g] {
				t.Fatalf("counted deselected gram %v", g)
			}
		}
	}
}

func TestPositionalOccurrencesRepeatedGramDecodedOnce(t *testing.T) {
	ix := index.New()
	ix.AddFile("r", "f", "", "sha", []byte(strings.Repeat("a", 200)))
	lazy, p := lazyOccurrences(ix, nil)
	needle := []byte("aaaaa")
	if got, want := occurrencePositions(lazy, needle, true), occurrencePositions(ix, needle, false); !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	if len(p.counted) != 1 || len(p.decoded) != 1 {
		t.Fatalf("counted %v, decoded %v", p.counted, p.decoded)
	}
}
